default: &default
  adapter: postgresql
  encoding: unicode
  url: <%= ENV['DATABASE_URL'] %>
  max_connections: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: demo_development

test:
  <<: *default
  database: demo_test
production:
  primary: &primary_production
    <<: *default
    database: demo_production
    username: demo
    password: <%= ENV["DEMO_DATABASE_PASSWORD"] %>
  cache:
    <<: *primary_production
    database: demo_production_cache
    migrations_paths: db/cache_migrate
  queue:
    <<: *primary_production
    database: demo_production_queue
    migrations_paths: db/queue_migrate
  cable:
    <<: *primary_production
    database: demo_production_cable
    migrations_paths: db/cable_migrate
