default: &default
  adapter: postgresql
  encoding: unicode
  host: 127.0.0.1
  username: postgres
  password: <%= ENV["POSTGRES_PASSWORD"] %>
  pool: 5

development:
  <<: *default
  database: devs_development

test:
  <<: *default
  database: devs_test

production:
  url: <%= ENV["DATABASE_URL"] %>
